Repository abdullahzen/W18S341_UB1, pull requests merged in 2018-02, with the labels that each got.

#27 Travis yml implementation
  .env
  .env.travis
  .gitignore
  .travis.yml
  phpunit.xml
  test
Labels: environment

#33 Minor fix - forgot to remove an alert from debugging mode
  public/js/register.js
Labels: back-end, bug

#40 Fix in register front-end (fix for duplicated fields)
  resources/views/modals/register.blade.php
Labels: bug

#42 Fixed DB errors.
  .env
  app/Http/Controllers/ClientControllerHelper.php
  config/database.php
  database/DB_Feb16/DB.sql
  database/database_files.sql
Labels: bug

#44 Added a new logo for the website
  public/assets/images/logo_new.svg
  resources/views/includes/headerfooter.blade.php
Labels: enhancement
