Repository abdullahzen/W18S341_UB1, pull requests merged in 2018-03, with the labels that each got.

#67 Made a few changes to the db and added an extra table
  database/database.sql
Labels: bug, enhancement

#64 DB query fixes and bug fixes
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/ClientControllerHelper.php
  resources/views/modals/userProfile.blade.php
Labels: back-end, bug, environment

#72 DB fixes and query fixes
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/ClientControllerHelper.php
  database/database.sql
  resources/views/pages/newquestion.blade.php
Labels: back-end, bug

#90 Fixes after merge
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/ClientControllerHelper.php
  resources/views/includes/lang/c.blade.php
  resources/views/includes/lang/java.blade.php
  resources/views/includes/lang/js.blade.php
  resources/views/includes/lang/php.blade.php
  resources/views/pages/post.blade.php
Labels: bug

#95 Backend implementation of the top 3 questions (most upvoted)
  app/Http/Controllers/ClientControllerHelper.php
  resources/views/includes/lang/c.blade.php
  resources/views/includes/lang/java.blade.php
  resources/views/includes/lang/js.blade.php
  resources/views/includes/lang/php.blade.php
Labels: back-end

#96 Kl enhancement v2
  app/Http/Controllers/ClientController.php
  public/js/editProfile.js
  public/js/editQuestion.js
  public/js/post.js
  public/js/userProfile.js
  resources/views/includes/lang/c.blade.php
  resources/views/includes/lang/java.blade.php
  resources/views/includes/lang/js.blade.php
  resources/views/includes/lang/php.blade.php
  resources/views/modals/edit.blade.php
  resources/views/modals/editProfile.blade.php
  resources/views/modals/login.blade.php
  resources/views/modals/register.blade.php
  resources/views/pages/favourites.blade.php
  resources/views/pages/newquestion.blade.php
  resources/views/pages/post.blade.php
  routes/web.php
Labels: enhancement, main-feature

#100 Restrictions and many minor fixes
  app/Http/Controllers/ClientController.php
  public/js/answer.js
  public/js/post.js
  resources/views/includes/lang/c.blade.php
  resources/views/includes/lang/java.blade.php
  resources/views/includes/lang/js.blade.php
  resources/views/includes/lang/php.blade.php
  resources/views/pages/favourites.blade.php
  resources/views/pages/newquestion.blade.php
  resources/views/pages/post.blade.php
  resources/views/pages/search.blade.php
Labels: bug, enhancement

#102 Fixed newQuestion design layout.
  resources/views/pages/newquestion.blade.php
Labels: bug

#118 Adding new category feature and travis fix
  .env.travis
  .travis.yml
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/ClientControllerHelper.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2014_10_12_100000_create_password_resets_table.php
  database/migrations/database.sql
  phpunit.xml
  public/js/addCategory.js
  public/js/answer.js
  public/js/editQuestion.js
  public/js/login.js
  public/js/mainpage.js
  public/js/post.js
  public/js/register.js
  resources/views/includes/headerfooter.blade.php
  resources/views/includes/leftmenu.blade.php
  resources/views/modals/edit.blade.php
  resources/views/modals/login.blade.php
  resources/views/modals/register.blade.php
  resources/views/pages/category.blade.php
  resources/views/pages/favourites.blade.php
  resources/views/pages/homepage.blade.php
  resources/views/pages/newCategory.blade.php
  resources/views/pages/newquestion.blade.php
  resources/views/pages/post.blade.php
  resources/views/pages/search.blade.php
  routes/web.php
  tests/Feature/ExampleTest.php
Labels: back-end, front-end, secondary-feature

#120 Kl form restriction handling
  app/Http/Controllers/ClientController.php
  public/js/editProfile.js
  public/js/register.js
  resources/views/includes/headerfooter.blade.php
  resources/views/includes/modals.blade.php
  resources/views/modals/login.blade.php
  resources/views/modals/register.blade.php
  resources/views/pages/category.blade.php
  resources/views/pages/homepage.blade.php
  resources/views/pages/newCategory.blade.php
  resources/views/pages/newquestion.blade.php
  resources/views/pages/post.blade.php
  resources/views/pages/search.blade.php
  routes/web.php
Labels: bug

#129 Multiple fixes after the last merge and homepage optimization
  public/css/customRegisterLoginStyles.css
  resources/views/includes/headerfooter.blade.php
  resources/views/modals/edit.blade.php
  resources/views/modals/login.blade.php
  resources/views/modals/register.blade.php
  resources/views/pages/category.blade.php
  resources/views/pages/homepage.blade.php
Labels: bug

#123 Kl form restriction handling
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/ClientControllerHelper.php
  app/Http/Middleware/VerifyCsrfToken.php
  composer.lock
  config/app.php
  database/notification.sql
  public/css/ourstyle.css
  public/js/mainpage.js
  resources/views/includes/headerfooter.blade.php
  resources/views/includes/modals.blade.php
  resources/views/includes/notification.blade.php
  resources/views/includes/postbox.blade.php
  resources/views/modals/favourite.blade.php
  resources/views/modals/notifications.blade.php
  resources/views/pages/category.blade.php
  resources/views/pages/favourites.blade.php
  resources/views/pages/newCategory.blade.php
  resources/views/pages/newquestion.blade.php
  resources/views/pages/post.blade.php
  resources/views/pages/search.blade.php
  routes/web.php
Labels: Optimization, back-end, bug, enhancement, secondary-feature

#135 Bug fixes for rank and other places
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/ClientControllerHelper.php
  database/database.sql
  resources/views/includes/lang/c.blade.php
  resources/views/includes/lang/java.blade.php
  resources/views/includes/lang/js.blade.php
  resources/views/includes/lang/php.blade.php
  resources/views/modals/rank.blade.php
  routes/web.php
Labels: back-end, bug

#126 Selenium UI Test Cases
  UI Testing/Add Category/Add Category Test Log 20-03-2018.php
  UI Testing/Add Category/Add Category Test Script.groovy
  UI Testing/Add Category/Add Category Test Suite.php
  UI Testing/Answer/Answer Test Log 20-03-2018.php
  UI Testing/Answer/Answer Test Suite.php
  UI Testing/Answer/Answer.groovy
  UI Testing/Category Bar/Category Bar Navigation Test Suite.php
  UI Testing/Category Bar/Category Bar Test Log 20-03-2018.php
  UI Testing/Category Bar/CategoryBar.groovy
  UI Testing/Edit Profile/Edit Profile Test Log 20-03-2018.php
  UI Testing/Edit Profile/Edit Profile Test Suite.php
  UI Testing/Edit Profile/EditProfile.groovy
  UI Testing/Favourite/Favourite Test Log 20-03-2018.php
  UI Testing/Favourite/Favourite Test Suite.php
  UI Testing/Favourite/Favourite.groovy
  UI Testing/Login/Login Test Log 20-03-2018.php
  UI Testing/Login/Login Test Suite.php
  UI Testing/Login/Login.groovy
  UI Testing/New Post/New Post Test Log 20-03-2018.php
  UI Testing/New Post/New Post Test Suite.php
  UI Testing/New Post/NewPost.groovy
  UI Testing/Register/Register Test Log 20-03-2018.php
  UI Testing/Register/Register Test Suite.php
  UI Testing/Register/Register.groovy
  UI Testing/Search/Search Test Log 20-03-2018.php
  UI Testing/Search/Search Test Suite.php
  UI Testing/Search/Search.groovy
  UI Testing/UpVote DownVote/UpVote DownVote Test Log 20-03-2018.php
  UI Testing/UpVote DownVote/UpVote DownVote Test Suite.php
  UI Testing/UpVote DownVote/UpvoteDownvote.groovy
Labels: enhancement, environment, front-end

#137 Sprint 4 fixes and public user profile
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/ClientControllerHelper.php
  public/css/ourstyle.css
  resources/views/includes/headerfooter.blade.php
  resources/views/includes/postbox.blade.php
  resources/views/modals/userProfile.blade.php
  resources/views/pages/post.blade.php
  resources/views/pages/publicProfile.blade.php
  routes/web.php
Labels: back-end, bug, enhancement, front-end

#139 Notif modal kl
  DEMO/Notification DEMO.png
  app/Http/Controllers/ClientController.php
  app/Http/Controllers/ClientControllerHelper.php
  database/database.sql
  database/notification.sql
  public/js/answer.js
  public/js/mainpage.js
  public/js/post.js
  resources/views/includes/headerfooter.blade.php
  resources/views/includes/modals.blade.php
  resources/views/includes/notification.blade.php
  resources/views/includes/postbox.blade.php
  resources/views/modals/notifications.blade.php
  resources/views/pages/category.blade.php
  resources/views/pages/notifications.blade.php
  resources/views/pages/search.blade.php
  routes/web.php
Labels: enhancement

#142 Kl sprint4 enhance
  app/Http/Controllers/ClientController.php
  app/Http/Middleware/TrustProxies.php
  composer.json
  composer.lock
  public/css/ourstyle.css
  public/js/mainpage.js
  resources/views/includes/headerfooter.blade.php
  resources/views/includes/innerNavBar.blade.php
  resources/views/includes/leftmenu.blade.php
  resources/views/includes/postbox.blade.php
  resources/views/modals/edit.blade.php
  resources/views/modals/favourite.blade.php
  resources/views/pages/category.blade.php
  resources/views/pages/homepage.blade.php
  resources/views/pages/newCategory.blade.php
  resources/views/pages/newquestion.blade.php
  resources/views/pages/notifications.blade.php
  resources/views/pages/post.blade.php
  resources/views/pages/publicProfile.blade.php
  resources/views/pages/search.blade.php
Labels: Optimization, bug, enhancement

#146 Kl visual sorting
  app/Http/Controllers/ClientControllerHelper.php
  public/js/mainpage.js
  resources/views/includes/loading.blade.php
  resources/views/pages/category.blade.php
  resources/views/pages/homepage.blade.php
  resources/views/pages/sortedHomepage.blade.php
  routes/web.php
Labels: Optimization, enhancement
